# Generated by Django 6.1.1 on 2026-09-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(help_text='e.g. Backend Developer', max_length=200),
        ),
    ]
