# Generated by Django 6.1.1 on 2026-09-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_education_experience_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Web Application Development with Python', max_length=200)),
                ('issuer', models.CharField(help_text='e.g. NSDA', max_length=150)),
                ('level', models.CharField(blank=True, help_text='e.g. Level-4, 360 hours', max_length=50)),
                ('year', models.CharField(blank=True, max_length=50)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
