# Generated by Django 6.1.1 on 2026-09-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0006_alter_skill_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon_class',
            field=models.CharField(blank=True, help_text='খালি রাখলে Name অনুযায়ী অটো আইকন সেট হবে।', max_length=100, null=True),
        ),
    ]
