# Generated by Django 6.1.1 on 2026-09-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0007_skill_icon_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('language', 'Language'), ('framework', 'Framework'), ('database', 'Database'), ('tool', 'Tool'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
